"""Added t_deadline to UserBook

Revision ID: bc46d3501cad
Revises: 8ce0d0ae6bcb
Create Date: 2024-02-19 01:00:04.054989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc46d3501cad'
down_revision = '8ce0d0ae6bcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userbook', schema=None) as batch_op:
        batch_op.add_column(sa.Column('t_deadline', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userbook', schema=None) as batch_op:
        batch_op.drop_column('t_deadline')

    # ### end Alembic commands ###
